"""empty message

Revision ID: 8ebbbb147aa3
Revises: beefe648bb5a
Create Date: 2024-06-08 19:49:26.063362

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ebbbb147aa3"
down_revision: Union[str, None] = "beefe648bb5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flat_coins", sa.Column("issuer_wallet_public_key", sa.String(), nullable=False)
    )
    op.add_column(
        "flat_coins",
        sa.Column("issuer_wallet_private_key", sa.String(), nullable=False),
    )
    op.add_column(
        "flat_coins", sa.Column("holder_wallet_public_key", sa.String(), nullable=False)
    )
    op.add_column(
        "flat_coins",
        sa.Column("holder_wallet_private_key", sa.String(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flat_coins", "holder_wallet_private_key")
    op.drop_column("flat_coins", "holder_wallet_public_key")
    op.drop_column("flat_coins", "issuer_wallet_private_key")
    op.drop_column("flat_coins", "issuer_wallet_public_key")
    # ### end Alembic commands ###
