"""empty message

Revision ID: b33b14637ef1
Revises: 8ebbbb147aa3
Create Date: 2024-06-08 20:44:15.061124

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b33b14637ef1"
down_revision: Union[str, None] = "8ebbbb147aa3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commodity_coins",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("issuer_wallet_public_key", sa.String(), nullable=False),
        sa.Column("issuer_wallet_private_key", sa.String(), nullable=False),
        sa.Column("holder_wallet_public_key", sa.String(), nullable=False),
        sa.Column("holder_wallet_private_key", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp(0)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_commodity_coins_address"), "commodity_coins", ["address"], unique=True
    )
    op.create_index(
        op.f("ix_commodity_coins_name"), "commodity_coins", ["name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_commodity_coins_name"), table_name="commodity_coins")
    op.drop_index(op.f("ix_commodity_coins_address"), table_name="commodity_coins")
    op.drop_table("commodity_coins")
    # ### end Alembic commands ###
