"""empty message

Revision ID: beefe648bb5a
Revises: 
Create Date: 2024-06-08 14:30:06.048237

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "beefe648bb5a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flat_coins",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp(0)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_flat_coins_address"), "flat_coins", ["address"], unique=True
    )
    op.create_index(op.f("ix_flat_coins_name"), "flat_coins", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_flat_coins_name"), table_name="flat_coins")
    op.drop_index(op.f("ix_flat_coins_address"), table_name="flat_coins")
    op.drop_table("flat_coins")
    # ### end Alembic commands ###
